name             'acceptance'
maintainer       'Patrick Wright'
maintainer_email 'patrick@getchef.com'
license          'All rights reserved'
description      'Creates test nodes with chef metal and includes basic test recipes'
version          '0.1.0'
