name             'client'
maintainer       'Patrick Wright'
maintainer_email 'patrick@getchef.com'
license          'All rights reserved'
description      'Creates test node with chef-metal. Not intended to be uploaded to chef server'
version          '0.1.0'
